## 입력변수 2개 이상

* 예습시간 x1, 복습시간 x2와 pass fail 상관관계

In [1]:
import numpy as np

x_data = np.array([[2,4],[4,11],[6,6],[8,5],[10,7],[12,16],[14,8],[16,3],[18,7]])
t_data = np.array([0,0,0,0,1,1,1,1,1]).reshape(9,1)

W = np.random.rand(2,1) # 2x1 행렬
b = np.random.rand(1)

print(W, W.shape, b, b.shape)

[[0.93206566]
 [0.41674214]] (2, 1) [0.42576308] (1,)


In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def loss_func(x, t):
    
    delta = 1e-7 # log 무한대 발산 방지(입력값 0 안되게)
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    # cross-entropy
    return -np.sum(t*np.log(y + delta) + (1-t)*np.log((1-y)+delta))

In [3]:
def numerical_derivative(f,x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags = ['multi_index'], op_flags = ['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx]  = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad
        
        
        

In [4]:
def predict(x):
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    if y > 0.5:
        result = 1 #True
    else:
        result = 0 #False
        
    return y, result


In [5]:
learning_rate = 1e-2 # 발산하는 경우, 1e-3, 1e-6 등으로 바꾸어서 실행

f = lambda x : loss_func(x_data, t_data) # f(x) = loss_func(x_data, t_data)

print("initial error value = ", loss_func(x_data,t_data), "initial W = ", W, "\n", " , b = ", b)

for step in range(80001):
    
    W -= learning_rate*numerical_derivative(f, W)
    b -= learning_rate*numerical_derivative(f, b)
    
    if(step%400 == 0):
        print("step = ", step, "error value = ", loss_func(x_data, t_data), "W = ", W, ", b = ", b)

initial error value =  31.19575681650308 initial W =  [[0.93206566]
 [0.41674214]] 
  , b =  [0.42576308]
step =  0 error value =  20.39188643306009 W =  [[0.73268845]
 [0.15772992]] , b =  [0.38661033]
step =  400 error value =  2.2365895958437383 W =  [[ 0.42498386]
 [-0.08403081]] , b =  [-2.69382]
step =  800 error value =  1.5768609581311734 W =  [[ 0.53960156]
 [-0.02492444]] , b =  [-4.30652414]
step =  1200 error value =  1.2722009918051298 W =  [[0.62601447]
 [0.00998789]] , b =  [-5.40663823]
step =  1600 error value =  1.09322529931993 W =  [[0.6958935 ]
 [0.03497125]] , b =  [-6.25069955]
step =  2000 error value =  0.9731703488277952 W =  [[0.75485921]
 [0.05492208]] , b =  [-6.94220556]
step =  2400 error value =  0.8856164596820636 W =  [[0.80602436]
 [0.07202629]] , b =  [-7.5327762]
step =  2800 error value =  0.8180133889048571 W =  [[0.85129555]
 [0.08741846]] , b =  [-8.05171004]
step =  3200 error value =  0.7636224909162487 W =  [[0.89192936]
 [0.10174628]] , b = 

step =  31200 error value =  0.1718765434711879 W =  [[1.77790957]
 [0.699778  ]] , b =  [-20.119239]
step =  31600 error value =  0.17001448624230023 W =  [[1.78429462]
 [0.70454784]] , b =  [-20.20523796]
step =  32000 error value =  0.1681918025393585 W =  [[1.79061425]
 [0.70926314]] , b =  [-20.29032226]
step =  32400 error value =  0.16640726656229315 W =  [[1.79686979]
 [0.71392512]] , b =  [-20.3745109]
step =  32800 error value =  0.16465970266173535 W =  [[1.80306249]
 [0.71853493]] , b =  [-20.45782231]
step =  33200 error value =  0.16294798280196476 W =  [[1.80919359]
 [0.72309372]] , b =  [-20.54027438]
step =  33600 error value =  0.1612710241767306 W =  [[1.81526428]
 [0.72760258]] , b =  [-20.62188442]
step =  34000 error value =  0.15962778696730426 W =  [[1.82127573]
 [0.73206259]] , b =  [-20.70266926]
step =  34400 error value =  0.15801727223292436 W =  [[1.82722906]
 [0.73647476]] , b =  [-20.78264522]
step =  34800 error value =  0.1564385199243883 W =  [[1.8331

step =  62800 error value =  0.09181302665172006 W =  [[2.14744908]
 [0.96814606]] , b =  [-25.05111262]
step =  63200 error value =  0.09127199300907236 W =  [[2.1509475 ]
 [0.97062743]] , b =  [-25.09745444]
step =  63600 error value =  0.09073725227892454 W =  [[2.1544259 ]
 [0.97309373]] , b =  [-25.14352586]
step =  64000 error value =  0.09020869587718038 W =  [[2.15788448]
 [0.97554515]] , b =  [-25.18932999]
step =  64400 error value =  0.08968621769375938 W =  [[2.16132347]
 [0.97798186]] , b =  [-25.2348699]
step =  64800 error value =  0.08916971402272289 W =  [[2.1647431 ]
 [0.98040404]] , b =  [-25.28014858]
step =  65200 error value =  0.08865908349480256 W =  [[2.16814357]
 [0.98281185]] , b =  [-25.325169]
step =  65600 error value =  0.0881542270121414 W =  [[2.1715251 ]
 [0.98520547]] , b =  [-25.36993407]
step =  66000 error value =  0.08765504768521949 W =  [[2.1748879 ]
 [0.98758506]] , b =  [-25.41444663]
step =  66400 error value =  0.08716145077187555 W =  [[2.1

In [6]:
test_data = np.array([3,17]) # (예습, 복습) = (3,17)
predict(test_data)

(array([0.12868053]), 0)

In [7]:
test_data = np.array([5,8]) # (예습, 복습) = (5,8)
predict(test_data)

(array([0.00099031]), 0)

In [8]:
test_data = np.array([7,21]) # (예습, 복습) = (7,21)
predict(test_data)

(array([0.99998955]), 1)

In [11]:
test_data = np.array([12,0]) # (예습, 복습) = (12,0)
predict(test_data)

(array([0.63499525]), 1)