* 입력 변수가 하나 이상인 다변수 함수의 경우, 입력변수는 서로 독립적이기 때문에 수치미분 또한 변수의 개수만큼 개별적으로 계산하여야 함

In [9]:
import numpy as np

def numerical_derivative(f,x):
# f = 다변수함수, x = 모든 변수 포함나는 numpy 객체(배열, 행렬...)
    delta_x = 1e-4
    grad = np.zeros_like(x) # 계산된 수치미분 값 저장 변수
    print("debug 1. initial input variable =", x)
    print("debug 2. initial grad =", grad)
    print("======================================")
    
    
    it = np.nditer(x, flags = ['multi_index'], op_flags = ['readwrite'])
    # 모든 입력변수에 대해 편미분하기 위해 iterator 획득
    
    while not it.finished:
        idx = it.multi_index
        
        print("debug 3. idx = ", idx, ", x[idx] = ", x[idx])
        
        tmp_val = x[idx] # 원래 값 보관 (numpy 타입은 mutable이기 때문)
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print("debug 4. grad[idx] =", grad[idx])
        print("debug 5. grad =", grad)
        print("======================================")
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad
        

## 예제

* 1변수 함수 
> f(x) = x^2 / f'(3) 

In [10]:
def func1(input_obj):
    x = input_obj[0]
    
    return x**2

In [11]:
numerical_derivative(func1, np.array([3.0]))

debug 1. initial input variable = [3.]
debug 2. initial grad = [0.]
debug 3. idx =  (0,) , x[idx] =  3.0
debug 4. grad[idx] = 6.000000000012662
debug 5. grad = [6.]


array([6.])

* 2변수 함수
> f(x,y) = 2x + 3xy + y^3 / f'(1.0, 2.0)

In [13]:
# 입력변수 2개인 함수 선언(x,y)
def func2(input_obj):
    
    x = input_obj[0]
    y = input_obj[1]
    
    return (2*x + 3*x*y + np.power(y,3))

In [14]:
#(x,y) = (1.0, 2.0) 에서의 편미분 값
input = np.array([1.0, 2.0])
numerical_derivative(func2, input)

debug 1. initial input variable = [1. 2.]
debug 2. initial grad = [0. 0.]
debug 3. idx =  (0,) , x[idx] =  1.0
debug 4. grad[idx] = 7.999999999990237
debug 5. grad = [8. 0.]
debug 3. idx =  (1,) , x[idx] =  2.0
debug 4. grad[idx] = 15.000000010019221
debug 5. grad = [ 8.         15.00000001]


array([ 8.        , 15.00000001])

* 4변수 함수
> f(w,x,y,z) = wx + xyz + 3w + zy^2 / f'(1.0, 2.0, 3.0, 4.0)

In [15]:
# 입력변수 4개인 함수
def func3(input_obj):
    
    w = input_obj[0,0]
    x = input_obj[0,1]
    y = input_obj[1,0]
    z = input_obj[1,1]
    
    return (w*x + x*y*z + 3*w + z*np.power(y,2))

In [16]:
# 입력을 2x2 행렬로 구성함
input = np.array([[1.0, 2.0], [3.0, 4.0]])

numerical_derivative(func3, input)

debug 1. initial input variable = [[1. 2.]
 [3. 4.]]
debug 2. initial grad = [[0. 0.]
 [0. 0.]]
debug 3. idx =  (0, 0) , x[idx] =  1.0
debug 4. grad[idx] = 5.000000000023874
debug 5. grad = [[5. 0.]
 [0. 0.]]
debug 3. idx =  (0, 1) , x[idx] =  2.0
debug 4. grad[idx] = 13.00000000000523
debug 5. grad = [[ 5. 13.]
 [ 0.  0.]]
debug 3. idx =  (1, 0) , x[idx] =  3.0
debug 4. grad[idx] = 32.00000000006753
debug 5. grad = [[ 5. 13.]
 [32.  0.]]
debug 3. idx =  (1, 1) , x[idx] =  4.0
debug 4. grad[idx] = 15.000000000000568
debug 5. grad = [[ 5. 13.]
 [32. 15.]]


array([[ 5., 13.],
       [32., 15.]])