## dot product

In [1]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[-1,-2],
              [-3,-4],
              [-5,-6]])

# (2x3) dot (3x2) == (2x2) 행렬
C = np.dot(A,B)

print(C)

[[-22 -28]
 [-49 -64]]


* numpy broadcast
> 크기가 다른 두 행렬간에도 사칙연산을 하게 해줌
>>차원이 작은 쪽이 큰 쪽의 행 단위로 반복적으로 크기를 맞춘 후에 계산

In [3]:
A = np.array([[1,2], [3,4]])
b = 5

print(A+b)

[[6 7]
 [8 9]]


In [2]:
C = np.array([[1,2],[3,4]])
D = np.array([4,5])

print(C.ndim, D.ndim)


print(C+D)


2 1
[[5 7]
 [7 9]]


## 전치행렬(transpose)

In [4]:
A = np.array([[1,2],[3,4],[5,6]]) # 3x2 행렬

B = A.T # A의 전치행렬, 2x3행렬

print(A.shape, B.shape)
print(A)

print(B)

(3, 2) (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [6]:
# vector 전치행렬
C = np.array([1,2,3,4,5]) # vector, matrix 아님
D = C.T

print(D)

E = C.reshape(1,5)
F = E.T
print(E)
print(F)

[1 2 3 4 5]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


## numpy 행렬 indexing / slicing

In [11]:
A = np.array([10,20,30,40,50,60]).reshape(3,2)

print(A.shape)
print(A)

(3, 2)
[[10 20]
 [30 40]
 [50 60]]


In [14]:
print(A[0,0]) # 1행 1열 = 10
print(A[0][0])

print(A[2,1]) # 3행 2열 = 60

10
10
60


In [15]:
print("A[0:1, 1:2] ==", A[0:-1, 1:2])
# 0부터 -2까지(-1-1)의 행, 1부터 1까지(2-1)의 열 만족하는 데이터


A[0:1, 1:2] == [[20]
 [40]]


In [17]:
print(A[:,0]) # 모든 행, 첫번째 열
print(A[:,:]) # 모든 행, 모든 열

[10 30 50]
[[10 20]
 [30 40]
 [50 60]]


## numpy 행렬 iterator

* numpy iterator는 C++, Java iterator 처럼 next() 메서드를 통해 데이터 값을 처음부터 끝까지 순차적으로 읽어들이는 방법을 제공

In [21]:
# iterator 예제

A = np.array([ [10, 20, 30, 40], [50, 60, 70, 80] ]) 

print(A, "\n") 
print("A.shape ==", A.shape, "\n") 

# 행렬 A 의 itrator 생성

it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])
    
while not it.finished:
    
    idx = it.multi_index
    
    print("current value =>", A[idx])
    
    it.iternext()

[[10 20 30 40]
 [50 60 70 80]] 

A.shape == (2, 4) 

current value => 10
current value => 20
current value => 30
current value => 40
current value => 50
current value => 60
current value => 70
current value => 80
